language: php

notifications:
  email:
    on_success: never
    on_failure: change
    
dist: precise

php:
# Taking out php 5.3 support
# https://bbpress.trac.wordpress.org/ticket/3127
# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
# - 5.3
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - composer update
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  # ###########################################################################
  # THE FOLLOWING IS FROM:
  # https://github.com/JDGrimes/wp-browser-travis-demo/blob/master/.travis.yml
  # ###########################################################################
  # Define vars.
  - export WP_VERSION=master
  - export WP_DEVELOP_DIR=/tmp/wordpress
  - export WP_CORE_DIR=/tmp/wordpress/src
  - export WP_CEPT_SERVER='127.0.0.1:4445'
  # Start up a web server.
  - php -S "$WP_CEPT_SERVER" -t "$WP_CORE_DIR" >/dev/null 2>&1 &
  # Start up the webdriver.
  - phantomjs --webdriver=4444 >/dev/null 2>&1 &
  # Install Codeception and WP Browser.
  # Doing this last gives the webdriver and server time to start up.
  - composer install --prefer-source

# script: phpunit --debug
script:
  - vendor/bin/codecept run --debug

after_script:
  - pwd;
  - ls -alh /home/travis/build/BoldGrid/boldgrid-inspirations;
  - ls -alh /home/travis/build/BoldGrid/boldgrid-inspirations/tests;
  - ls -alh /home/travis/build/BoldGrid/boldgrid-inspirations/tests/codeception;
  - ls -alh /home/travis/build/BoldGrid/boldgrid-inspirations/tests/codeception/_output;
  - cat /home/travis/build/BoldGrid/boldgrid-inspirations/tests/codeception/_output/basicCept.fail.html;